name: Build job

on: push

jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Maven test
        run: mvn test -B
